Update README.md
vtex-apps/store-link pull request #14
Opened 2020-06-24 21:07 UTC by guerreirobeatriz

2020-06-24 21:13 UTC, kaisermann approved these changes

2020-06-24 21:13 UTC, kaisermann commented on docs/README.md
>  }
```suggestion
  }
```

2020-06-24 21:19 UTC, klzns requested changes

2020-06-24 21:19 UTC, klzns commented on docs/README.md
>  }
👀 
```suggestion
 }
```

2020-06-24 21:19 UTC, klzns commented on docs/README.md
> +To build URLs with variables related to the product specifications, you should use the following format: `{specificationGroups.|{{groupName}}|.specifications.|{{specificationName}}|}`, replacing the
It's a bit confusing. Maybe this?
```suggestion
To build URLs with variables related to the product specifications, you should use the following format: `{specificationGroups.GROUP NAME HERE.specifications.SPECIFICATION NAME HERE}`, replacing the curly brackets according to your scenario. For example:
```

2020-06-24 21:19 UTC, klzns commented on docs/README.md
> +In the example above, `App Data` is the specification group name and `vtex-url` is the product specification name.
I would change the above example to a more common one:

`{specificationGroups.Design.specifications.Dimensions}`

2020-06-24 21:29 UTC, kaisermann commented on docs/README.md
> +To build URLs with variables related to the product specifications, you should use the following format: `{specificationGroups.|{{groupName}}|.specifications.|{{specificationName}}|}`, replacing the
Maybe `[GROUP_NAME_HERE]`?

2020-06-25 12:44 UTC, Klynger approved these changes

2020-07-17 16:32 UTC, klzns approved these changes

2020-07-20 19:52 UTC, merged