Fix prop types of label and buttonProps being optional in code but not in typescript
vtex-apps/store-link pull request #15
Opened 2020-07-20 19:07 UTC by Klynger

#### What problem is this solving?

Optional props of the component not being optional in typescript too.

![image](https://user-images.githubusercontent.com/8517023/87975975-b8133280-caa2-11ea-88e2-a01d7470d59e.png)

#### How to test it?

1. https://klynger--storecomponents.myvtex.com/
2. Open the quickview
3. It should render ok

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/l2QE4Dep73Evk8OHK/giphy.gif)

2020-07-20 19:18 UTC, klzns requested changes

2020-07-20 19:18 UTC, klzns commented on react/StoreLink.tsx
> +  buttonProps?: Partial<ButtonProps>
I think we can type it differently. Making label required or children required.

2020-07-20 19:51 UTC, klzns approved these changes

2020-07-24 16:54 UTC, iaronaraujo approved these changes

2020-07-24 16:55 UTC, merged