Feature/title attribute
vtex-apps/store-link pull request #44
Opened 2021-10-01 19:58 UTC by gabriel-franciscon

#### What problem is this solving?

Thoe Store Link component accepts a `children` component, enabling a textless link. For example, a link with an icon only. This is bad for accessibility, and with a title attribute, we can solve this by improving the semantics of the links.

#### How to test it?

You can check the `title` attribute in the header's wishlist link.

[Workspace](https://titleattr--trackandfieldio.myvtex.com/)

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/48245692/135678627-74a6a38b-89c7-4495-a3e0-b5915cac6bca.png)
![image](https://user-images.githubusercontent.com/48245692/135678702-9b6f4291-4e9c-449a-859a-89bdab973d6f.png)
![image](https://user-images.githubusercontent.com/48245692/135678767-46674344-6870-4c94-a531-7f7dc99bdf28.png)

#### How does this PR make you feel? [:link:](http://giphy.com/)

![](https://media.giphy.com/media/xSM46ernAUN3y/giphy.gif)

2021-10-01 20:03 UTC, gabriel-franciscon commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! robot
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> - [ * ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually disappointed

2021-10-01 20:48 UTC, gabriel-franciscon commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! robot
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch (backwards-compatible bug fixes)
> * [x]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually disappointed

2021-10-05 20:19 UTC, camilavcoutinho approved these changes

2021-10-18 16:33 UTC, igorbrasileiro approved these changes

2021-10-18 16:33 UTC, igorbrasileiro commented on react/StoreLink.tsx
> +      {...{ title }}
Why did you need to do this? Is it to bypass the type check? If yes, you can pass directly, the Link Props from render-runtime was fixed https://github.com/vtex-apps/render-runtime/pull/627

2021-10-18 16:33 UTC, igorbrasileiro commented on react/__tests__/StoreLink.test.tsx
> +  const link = screen.getByTitle('View More')
Did you try to get the link by label?
```suggestion
test('StoreLink Component', () => {
  const { getByTitle } = render(<StoreLink href="/custom-link" label="View More" title="View More" />)

  const link = getByTitle('View More')
```

Remember to remove the screen from imports.

2021-10-18 16:33 UTC, igorbrasileiro commented on react/StoreLink.tsx
> +      {...{ title }}
```suggestion
      title={title}
```

2021-10-18 16:33 UTC, igorbrasileiro commented on react/ProductLink.tsx
> +      {...{ title }}
```suggestion
      title={ title }
```

2021-10-18 16:34 UTC, igorbrasileiro requested changes
Approved by mistake. Take a look at my request changes

2021-10-18 17:14 UTC, gabriel-franciscon commented on react/StoreLink.tsx
> +      {...{ title }}
@igorbrasileiro Yes, I used this to bypass the type check.
Updated, thanks for the feedback.

2021-10-18 17:14 UTC, gabriel-franciscon commented on react/__tests__/StoreLink.test.tsx
> +  const link = screen.getByTitle('View More')
@igorbrasileiro Updated.

2021-10-19 13:38 UTC, gabriel-franciscon commented
@igorbrasileiro, could you help me with the approval, please? I ended up making the changes manually.

2021-11-02 14:01 UTC, igorbrasileiro approved these changes
Great!

2021-11-11 16:41 UTC, gabriel-franciscon commented
Hello @icazevedo @mullerjk @pillarluz @guerreirobeatriz. Could you help me with reviewing this pull request, please?

2021-12-29 21:27 UTC, gabriel-franciscon commented
Hello @icazevedo @mullerjk @pillarluz @guerreirobeatriz. Could you help me with reviewing this pull request, please?

2022-01-07 18:42 UTC, igorbrasileiro commented
@gabriel-franciscon asap we will review and merge it. Sorry for the delay

2022-01-07 18:45 UTC, victorhmp commented on react/modules/useTitleAttr.ts
> +export const useTitleAttr = (title?: string, label = '') => {
```suggestion
export const useTitleAttribute = (title?: string, label = '') => {
```

2022-01-07 18:46 UTC, victorhmp commented on react/StoreLink.tsx
> +  const title = useTitleAttr(props.title, label)
```suggestion
  const title = useTitleAttribute(props.title, label)
```

2022-01-07 18:46 UTC, victorhmp commented on react/StoreLink.tsx
> +import { useTitleAttr } from './modules/useTitleAttr'
```suggestion
import { useTitleAttribute } from './modules/useTitleAttr'
```

2022-01-07 18:48 UTC, victorhmp commented on react/modules/useTitleAttr.ts
> + * @return The title atribute.
```suggestion
 * @return The title attribute.
```

2022-01-07 18:49 UTC, victorhmp approved these changes
Just a renaming suggestion :)

2022-01-07 19:09 UTC, gabriel-franciscon commented
@victorhmp Done. Thanks for the suggestions.

2022-01-24 14:00 UTC, gabriel-franciscon commented
@icazevedo Could you help me with reviewing this pull request, please?

2022-03-10 16:54 UTC, proudynyu commented
@victorhmp @icazevedo hello guys, how are you?
It is something else that we need to do in this PR? We are needing this new props to have a more clean conversation with the SEO people of our client and finish the task!
Thanks in advance! 🚀

2022-07-06 20:12 UTC, closed without merging